sudo: required
language: go
go:
- 1.8
install:
- bin/ci
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push orangeopensource/artifactory-resource; fi
env:
  matrix:
  - secure: OwpT9JFyqJZ94ixLRllK7bi5gwCXOAePRG4Xm9LDF8NMMnwiFGHTKkQYC7ZB2YbBLbgyHzRqStRCm1jeIYgonQrwWxv893xRiKAA3+c0qCQWyDh2UViEJahV2uWK2Zr/OjC9sfLQ21d7YDwYD8urgO0BfWEXSMGfd3dRDbrpGWViRzcC8JhEtMzhR+wEO4WidQITJNRujw1iFZQdsW6jPmQWEeR6N7BWlqU3GZHevodWb9ng73nOsTIiNIZJPCTl1y6pYyIBLJkeOQGmb5Mx4iyks4u213Pm4gg9NxjyVNOvEvt8lCZkR24I5xqdrUtdsPC3RnTa7enmFCkr+7f5u8LaS+pZZy5HTPQAP4/gaE2sVsTVfPo+MrHcCsXiTgrwxqd86e5JslrC7w4xk7L6WCDvxbo69+aVXQA7ifBoJPyNMKTJOLzlmSxaJZEDHPgawXAU8K18H4pkz4nxa6cE2H+djFxl2GsitUPZayau2M4wxlzQnQkuIKayQGMpudiiUqXHailgY+XjCS+/2iN1kh5SsUu7u657Zg+1xGdAHbqULJbQIs0XhbNLtduuP5+MqR4X0n4z4K9GQ6SlIa6N4YFBT3NUejjTTJiu5xKN/LECpbqBi1HiOwUHoFTNNq1J8LB2hP7Mc0YM1sQHyBDE9aMZdt6kDP7kSXL6g+aCBD8=
  - secure: Q0x6WY2ji/kIMiSbeAzwOXqG/vOfgYV9S9KuqCrlp3t93eYkQind6Wx57U4zTOVtgHK+qHKjz9NMYhngU8Xz3I4SqCsYsLMQoZOxL235CKu6ZZZNkY8Mja2d4qSd2DHAh7RQjAIH3kaoDpINV/vO1SDszxHs3Zhi6FRWAOUaNYj/B3B4y02kB0x3/sQA2nWZnc4/hdUOJz099SLbursWUsLbNzjq2mkgTc23/RQpkBITGN9q0xvt/Ht8E9TowmZggs8yqo8XESZVNGPepLSHbrRXfON4ibFHade0VaOKCvFeL71C9+x76j8t5Le2UQhF6BUKtmj9Tz3REU/GZWjg80nUDMPmiGpGtpudQ7o7IQYr0IjO2MpbgiYXeJCkE91BmgkYflq/siUDGR4MOkYHPuRap3/bESVrDcTuY6P3RXrY2gXScn2SOFxpHAqNStqANao8I7ZGM25UUwV3k0vsantLQn7enoURG2gme5PcKnMDbhn1sq1djL2SA6zLUS7g0/lGpx75qUD58Vi+lO4rl+76GnDM+lON8P54neAnMRaOa5aX2iBi/fkdik4ki49rVsV5oYi/J3+CQebloSrswiWB+vaTGIZx152grKPQb4viQ/s5EktbxpaKHx80xDqi450EUBsDxz9/SK+2bCepbjmIvBWGnyGVtw2hwmZEbhU=
